[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# Windows MSVC targets
[target.x86_64-pc-windows-msvc]
# linker = "link.exe" is default on Windows

[target.aarch64-pc-windows-msvc]
# linker = "link.exe" is default on Windows
